version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: EventManager
    ports:
      - "5432:5432"

  api:
    image: eventmanager-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"
      ASPNETCORE_HTTPS_PORT: "443"
      ASPNETCORE_Kestrel__Certificates__Default__Password: ""
      ASPNETCORE_Kestrel__Certificates__Default__Path: ""
      ASPNETCORE_JWT__SecretKey: "IssuerSigningKey"
      ASPNETCORE_JWT__Issuer: "http://localhost:8000/"
      ASPNETCORE_JWT__Audience: "http://localhost:8000/"
      ConnectionStrings__DefaultConnection: "Host=db;Database=EventManager;Username=postgres;Password=sa"
    ports:
      - "8000:80"
    depends_on:
      - db
    command: ["dotnet", "EventManager.WebAPI.dll"]